### ISSUE TITLE
[PE-D][Tester A] Delete Command Not Found

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-W13-1/tp#89]
Command: delete

![image.png](https://raw.githubusercontent.com/FeliciaBeatrice/ped/main/files/0a405983-c852-4578-a582-c55bc258972e.png)

Unable to find delete command even though it is in the list of commands.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: FeliciaBeatrice/ped#5

**Comment by markusteim** [comment]
debugger didn't note that userguide marks it to use delete account
